cherryApp.factory('Tabs', ['$rootScope', function($rootScope) {

    var svc = {
        showTabs: true,
        currentTabName: '',
        setTab: function (areaName) {
            svc.currentTabName = areaName;
        }
    };

    $rootScope.$on('$routeChangeSuccess', function (evt, current, previous) {
        svc.showTabs = current.showTabs;
        //svc.currentTabName = SelectedArea.getSelectedAreaName(); // not set yet :-(
    });

    $rootScope.$on('areaChange', function(evt, current) {
      svc.currentTabName = current;
    });

    // Can't find the right syntax !! Will listen to an event generated by SelectedArea instead
//    $rootScope.areaName = SelectedArea.getSelectedAreaName;
//    $rootScope.$watch('areaName()',svc.setTab(SelectedArea.getSelectedAreaName()));

  return svc;

}]);